### ISSUE TITLE
Router configuration name ( model name ) 

### ISSUE THREAD

**Issue by KnightofWhite** [assarbad/build-asuswrt-merlin#3]
As we know we have some standart model name make configuration
rt-n16
rt-n66u
rt-ac66u
rt-ac56u
rt-ac68u
For example you whant to compile rt-n66w ( not u ) 

Command ./debian-build-image RT-N66W 
give you make error because you haven't  that configuration name in asuswrt-merlin 'makepoints' names.
You need to correct script and change user enter name ( RT-N66W ) to standart ( RT-N66U ) before start compilling , because thats routers models haven't differents in hardware.

<s>And one more question. Can you add git pull command to script for updating repository before compilling and clearing ?

```
git pull
make clean
make kernelclean
make $ROUTER MODEL$
```

**Note:** this aspect of the ticket has been moved out to issue #4.
</s>

**Comment by assarbad** [comment]
Hey there, thanks.

I'll see to it that the router model name gets corrected to whatever the `Makefile` requires.

`git pull` makes no real sense. I think I should instead add something like an rc file that will be sourced at the very start and which can provide hook functions at different points.

See: just because _you_ think `git pull` would be a great thing to execute, this could be different for someone else. So the core script should be extensible, but on the other hand cater only the generic case.

I'll actually create another issue for that part of your ticket.

**Comment by assarbad** [comment]
Should be fixed. Please reopen if you find it's not.
