### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by LeeWiu** [assarbad/build-asuswrt-merlin#6]
I get this error while compiling with debian-build-image script
http://pastebin.com/xecgZR7h

```
root@ubuntu:/home/thx/test/asuswrt-merlin# uname -a
Linux ubuntu 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by assarbad** [comment]
I appreciate your defect reports, but this has evidently nothing to do with the script. Besides, right now the script hasn't even been adjusted to support the ARM routers.

Not every build error can automatically be blamed on this script. In fact only few can in general (specifically if programs cannot be executed, because they have not been made available).

This script is meant to simplify the preparation and cleanup, but it doesn't affect the build process in such a way that suddenly certain packages won't build. It's more likely that they don't build because there are issues and the code base wasn't tested for particular router models for a long time.
